// <auto-generated />
using AnimalShelterAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalShelterAPI.Migrations
{
    [DbContext(typeof(AnimalShelterAPIContext))]
    [Migration("20230712041752_WorkersCat")]
    partial class WorkersCat
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterAPI.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 7,
                            Name = "Soju",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 10,
                            Name = "Anju",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 2,
                            Name = "Evie",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 4,
                            Name = "Fred",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 22,
                            Name = "Lulu",
                            Species = "Dog"
                        });
                });

            modelBuilder.Entity("AnimalShelterAPI.Models.Worker", b =>
                {
                    b.Property<int>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("WorkerId");

                    b.ToTable("Workers");

                    b.HasData(
                        new
                        {
                            WorkerId = 1,
                            Age = 44,
                            Name = "John",
                            Role = "Vet"
                        },
                        new
                        {
                            WorkerId = 2,
                            Age = 32,
                            Name = "Steve",
                            Role = "Vet"
                        },
                        new
                        {
                            WorkerId = 3,
                            Age = 35,
                            Name = "Ellie",
                            Role = "Custodian"
                        },
                        new
                        {
                            WorkerId = 4,
                            Age = 33,
                            Name = "Annie",
                            Role = "Vet"
                        },
                        new
                        {
                            WorkerId = 5,
                            Age = 24,
                            Name = "Susan",
                            Role = "Greeter"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
